# Generated by Django 6.0.6 on 2026-06-23 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedparticipant',
            name='scanned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_participants', to='app.organiser'),
        ),
        migrations.AddField(
            model_name='event',
            name='invalid_qr_scans',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='rejected_scans',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
