# Generated by Django 6.0.6 on 2026-06-23 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_bookedparticipant_scanned_by_event_invalid_qr_scans_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedparticipant',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_participants', to='app.organiser'),
        ),
        migrations.AddField(
            model_name='bookedparticipant',
            name='reversed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
